services:
  ethercheck-backend:
    build:
      context: backend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./data/back:/app/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://ethercheck-backend:8080/api/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s  # даёт время на запуск

  ethercheck-front:
    build:
      context: frontend               # ← оставляем как было
      # dockerfile: Dockerfile        # ← УДАЛИ ЭТУ СТРОЧКУ, если была
    working_dir: /app
    # volumes:                        # ← можно закомментировать или удалить
    #   - ./data/front:/app/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  ethercheck-nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data:/app/data
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/nginx/ssl:ro
    depends_on:
      ethercheck-backend:
        condition: service_healthy
      ethercheck-front:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://ethercheck-nginx || exit 1" ]  # проверка на root
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    depends_on:
      ethercheck-nginx:
        condition: service_healthy  # ждёт, пока nginx здоров
    entrypoint: [ "/bin/sh","-c" ]
    command: echo "Certbot container ready"
    network_mode: host
