services:
  ethercheck-backend:
    build:
      context: backend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./data/back:/app/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "python -c 'import urllib.request,sys; sys.exit(0) if urllib.request.urlopen(\"http://localhost:8080/api/health\", timeout=3).getcode() == 200 else sys.exit(1)'" ]
      timeout: 3s
      retries: 5
      start_period: 30s

  ethercheck-front:
    build:
      context: frontend               # ← оставляем как было
      # dockerfile: Dockerfile        # ← УДАЛИ ЭТУ СТРОЧКУ, если была
    working_dir: /app
    # volumes:                        # ← можно закомментировать или удалить
    #   - ./data/front:/app/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "3000:3000"

  ethercheck-nginx:
    image: nginx:latest
    ports:
      - "47880:80"
    volumes:
      - ./data:/app/data
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/nginx/ssl:ro
    depends_on:
      ethercheck-backend:
        condition: service_healthy
      ethercheck-front:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://ethercheck-nginx || exit 1" ]  # проверка на root
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    depends_on:
      ethercheck-nginx:
        condition: service_healthy  # ждёт, пока nginx здоров
    entrypoint: [ "/bin/sh","-c" ]
    command: echo "Certbot container ready"
    network_mode: host
