services:
  ethercheck-backend:
    build:
      context: backend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./data/back:/app/data
    restart: unless-stopped

  ethercheck-front:
    build:
      context: frontend
    working_dir: /app
    volumes:
      - ./data/front:/app/data
    restart: unless-stopped

  ethercheck-nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data:/app/data
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/nginx/ssl:ro
    depends_on:
      - ethercheck-backend
      - ethercheck-front
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    depends_on:
      - ethercheck-nginx
    entrypoint: [ "/bin/sh","-c" ]
    command: echo "Certbot container ready"
    network_mode: host
